[package]
name = "JereIDE"
version.workspace = true
edition = "2024"

[[bin]]
name = "JereIDE"
path = "src/main.rs"

[dependencies]
eframe = "0.35"
egui_extras = { version = "0.35", features = ["all_loaders"] }
jereide-data = { path = "../datadir" }
jereide-settings = { path = "../settings" }
jereide-main-window = { path = "../main-window" }
