name: Feature Request
description: Suggest an idea for JereIDE (very appreciated!)
title: "[FEATURE] "
assignees:
  - Jeremy-Qian
type: Feature
labels: ["Not reviewed (yet)"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks! Feature requests are very appreciated!
        Make sure your request is for a NEW feature or enhancement in JereIDE.
        Put in a title above prefixed "[FEATURE]"
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: |
        I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A short description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
