[package]
name = "jereide-code"
version.workspace = true
edition = "2024"

[dependencies]
eframe = "0.35"
jereide-core = { path = "../core" }
jereide-editor = { path = "../editor" }
jereide-data = { path = "../datadir" }
jereide-settings = { path = "../settings" }
jereide-text = { path = "../text" }
jereide-syntax = { path = "../syntax" }
